# Generated by Django 4.2.1 on 2023-05-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Word')),
                ('gender', models.CharField(choices=[('mas', 'Masculine'), ('fem', 'Feminine'), ('neu', 'Neuter')], max_length=10, verbose_name='Gender')),
            ],
        ),
    ]
